package com.milkdromeda.blockpal.client.host;

import net.fabricmc.loader.api.FabricLoader;
import net.fabricmc.loader.api.ModContainer;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

/**
 * Writes the files a freshly-downloaded server needs before its first launch:
 * the EULA acceptance, {@code server.properties}, and (best-effort) a copy of the
 * running Blockpal jar so the hosted world has the AI companion too.
 */
final class HostConfig {

    private HostConfig() {}

    /** Writes {@code eula.txt}. Only ever called with {@code accepted=true} after the user ticks the box. */
    static void writeEula(Path serverDir, boolean accepted) throws IOException {
        Files.createDirectories(serverDir);
        Files.writeString(serverDir.resolve("eula.txt"),
                "# Minecraft EULA (https://aka.ms/MinecraftEULA) — accepted in Blockpal's host setup.\n"
                        + "eula=" + accepted + "\n",
                StandardCharsets.UTF_8);
    }

    static void writeServerProperties(Path serverDir, int javaPort, String motd, String levelName) throws IOException {
        Files.createDirectories(serverDir);
        String props = "# Generated by Blockpal host setup.\n"
                + "server-port=" + javaPort + "\n"
                + "motd=" + motd + "\n"
                + "level-name=" + levelName + "\n"
                // Floodgate lets Bedrock players join an online-mode Java server without a Java account,
                // so we keep accounts verified while still welcoming Bedrock.
                + "online-mode=true\n"
                + "max-players=100\n"
                + "allow-flight=true\n"
                + "spawn-protection=0\n"
                + "enable-command-block=true\n";
        Files.writeString(serverDir.resolve("server.properties"), props, StandardCharsets.UTF_8);
    }

    /**
     * Copies the running Blockpal mod jar into the server's mods folder so the hosted
     * world also runs Blockpal (companion + future minigames). Best-effort: in a dev
     * environment the mod isn't a single jar, so this is skipped rather than fatal.
     */
    static void copyBlockpalMod(Path modsDir) throws IOException {
        Files.createDirectories(modsDir);
        ModContainer self = FabricLoader.getInstance().getModContainer("blockpal").orElse(null);
        if (self == null) return;
        try {
            for (Path origin : self.getOrigin().getPaths()) {
                if (origin.getFileName() != null && origin.getFileName().toString().endsWith(".jar")) {
                    Files.copy(origin, modsDir.resolve("blockpal.jar"), StandardCopyOption.REPLACE_EXISTING);
                    return;
                }
            }
        } catch (UnsupportedOperationException ignored) {
            // Origin isn't a plain path (dev/nested) — nothing to copy.
        }
    }
}
